[package]
name = "Lumpy-Space-Princess"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenv = "0.15.0"
poise = "0.6.1"
regex = "1.11.1"
tokio = {  version = "1.43.0", features = ["rt-multi-thread"] }
